// <auto-generated />
using Boh.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Boh.Web.Data.Migrations
{
    [DbContext(typeof(BohDbContext))]
    partial class BohDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Boh.Web.Data.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(8192)
                        .HasColumnType("TEXT");

                    b.Property<double?>("DurationSec")
                        .HasColumnType("REAL");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVideo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<long>("UploadedAt")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UploadedById")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Sha256")
                        .IsUnique();

                    b.HasIndex("UploadedAt")
                        .IsDescending();

                    b.HasIndex("UploadedById");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("Boh.Web.Data.Entities.PostTag", b =>
                {
                    b.Property<int>("PostId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.HasKey("PostId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("PostTags");
                });

            modelBuilder.Entity("Boh.Web.Data.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Namespace")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("PostCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PostCount")
                        .IsDescending();

                    b.HasIndex("Namespace", "Name")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("Boh.Web.Data.Entities.TagAlias", b =>
                {
                    b.Property<int>("AliasTagId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CanonicalTagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AliasTagId");

                    b.HasIndex("CanonicalTagId");

                    b.ToTable("TagAliases");
                });

            modelBuilder.Entity("Boh.Web.Data.Entities.TagImplication", b =>
                {
                    b.Property<int>("ChildTagId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParentTagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ChildTagId", "ParentTagId");

                    b.HasIndex("ParentTagId");

                    b.ToTable("TagImplications");
                });

            modelBuilder.Entity("Boh.Web.Data.Entities.TagNamespace", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TagNamespaces");
                });

            modelBuilder.Entity("Boh.Web.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Boh.Web.Data.Entities.Post", b =>
                {
                    b.HasOne("Boh.Web.Data.Entities.User", "UploadedBy")
                        .WithMany()
                        .HasForeignKey("UploadedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("UploadedBy");
                });

            modelBuilder.Entity("Boh.Web.Data.Entities.PostTag", b =>
                {
                    b.HasOne("Boh.Web.Data.Entities.Post", "Post")
                        .WithMany("PostTags")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Boh.Web.Data.Entities.Tag", "Tag")
                        .WithMany("PostTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Boh.Web.Data.Entities.TagAlias", b =>
                {
                    b.HasOne("Boh.Web.Data.Entities.Tag", "AliasTag")
                        .WithMany()
                        .HasForeignKey("AliasTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Boh.Web.Data.Entities.Tag", "CanonicalTag")
                        .WithMany()
                        .HasForeignKey("CanonicalTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AliasTag");

                    b.Navigation("CanonicalTag");
                });

            modelBuilder.Entity("Boh.Web.Data.Entities.TagImplication", b =>
                {
                    b.HasOne("Boh.Web.Data.Entities.Tag", "ChildTag")
                        .WithMany()
                        .HasForeignKey("ChildTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Boh.Web.Data.Entities.Tag", "ParentTag")
                        .WithMany()
                        .HasForeignKey("ParentTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChildTag");

                    b.Navigation("ParentTag");
                });

            modelBuilder.Entity("Boh.Web.Data.Entities.Post", b =>
                {
                    b.Navigation("PostTags");
                });

            modelBuilder.Entity("Boh.Web.Data.Entities.Tag", b =>
                {
                    b.Navigation("PostTags");
                });
#pragma warning restore 612, 618
        }
    }
}
