using System.Security.Claims;
using System.Text.Json;
using Boh.Web;
using Boh.Web.Data.Entities;
using Boh.Web.Security;

namespace Boh.Tests;

/// <summary>
/// Guards the seams between the four places a theme id has to line up: the C# list, the
/// generated stylesheet, the auth ticket and the account form. Nothing here fails loudly at
/// runtime — a mismatched id just leaves the page rendering in the default colours — so the
/// checks have to be mechanical.
/// </summary>
public class ThemeTests
{
    public static TheoryData<string, string> AllPalettes()
    {
        var data = new TheoryData<string, string>();

        foreach (var theme in Themes.Light.Concat(Themes.Dark)) data.Add(theme.Id, theme.Mode);

        return data;
    }

    /// <summary>
    /// themes.css is generated by scripts/build-themes.py, so the list here and the blocks
    /// there are edited separately and can drift.
    /// </summary>
    [Theory]
    [MemberData(nameof(AllPalettes))]
    public async Task Every_palette_has_a_block_in_the_stylesheet(string id, string mode)
    {
        _ = mode;

        using var app = new TestApp();
        var css = await app.CreateClient().GetStringAsync("/css/themes.css");

        Assert.Contains($":root[data-theme-name=\"{id}\"]", css);
    }

    [Fact]
    public void The_two_palette_lists_do_not_overlap()
    {
        Assert.Empty(Themes.Light.Select(t => t.Id).Intersect(Themes.Dark.Select(t => t.Id)));
    }

    [Fact]
    public void Each_list_reports_the_mode_it_is_filed_under()
    {
        Assert.All(Themes.Light, t => Assert.Equal(Themes.LightMode, t.Mode));
        Assert.All(Themes.Dark, t => Assert.Equal(Themes.DarkMode, t.Mode));
    }

    // ---- normalisation -------------------------------------------------

    /// <summary>
    /// A dark scheme selected for the light side would emit a data-theme-name whose palette
    /// assumes the opposite background — dark text on dark. Falling back to the stock look
    /// is the only safe reading.
    /// </summary>
    [Fact]
    public void A_palette_from_the_other_mode_is_rejected()
    {
        Assert.Null(Themes.Normalize("nord", Themes.LightMode));
        Assert.Null(Themes.Normalize("solarized-light", Themes.DarkMode));
    }

    [Theory]
    [InlineData(null)]
    [InlineData("")]
    [InlineData("no-such-theme")]
    [InlineData("NORD")]
    public void Anything_that_is_not_a_known_palette_is_rejected(string? id)
    {
        Assert.Null(Themes.Normalize(id, Themes.DarkMode));
    }

    [Fact]
    public void A_palette_belonging_to_the_mode_is_kept()
    {
        Assert.Equal("nord", Themes.Normalize("nord", Themes.DarkMode));
        Assert.Equal("solarized-light", Themes.Normalize("solarized-light", Themes.LightMode));
    }

    // ---- the map handed to the pre-paint script ------------------------

    [Fact]
    public void The_palette_map_carries_both_sides()
    {
        var map = Deserialize(Themes.PaletteMapJson("gruvbox-light", "dracula"));

        Assert.Equal("gruvbox-light", map[Themes.LightMode]);
        Assert.Equal("dracula", map[Themes.DarkMode]);
    }

    /// <summary>
    /// The script tests the looked-up value for truthiness, so an unset side has to be absent
    /// rather than present-and-null.
    /// </summary>
    [Fact]
    public void An_unset_side_is_left_out_of_the_map_entirely()
    {
        var map = Deserialize(Themes.PaletteMapJson(null, "nord"));

        Assert.False(map.ContainsKey(Themes.LightMode));
        Assert.Equal("nord", map[Themes.DarkMode]);
    }

    [Fact]
    public void The_map_is_valid_json_when_nothing_is_set()
    {
        Assert.Empty(Deserialize(Themes.PaletteMapJson(null, null)));
    }

    private static Dictionary<string, string> Deserialize(string json) =>
        JsonSerializer.Deserialize<Dictionary<string, string>>(json)!;

    // ---- the auth ticket -----------------------------------------------

    [Fact]
    public void The_ticket_carries_both_palettes()
    {
        var principal = UserPrincipal.Create(
            new User { Id = 1, Username = "someone", LightTheme = "catppuccin-latte", DarkTheme = "monokai" });

        Assert.Equal("catppuccin-latte", UserPrincipal.GetLightTheme(principal));
        Assert.Equal("monokai", UserPrincipal.GetDarkTheme(principal));
    }

    /// <summary>
    /// Null and "no claim" have to read back the same, because that is what
    /// <see cref="RevalidateUserEvents"/> compares the row against when deciding whether the
    /// cookie has gone stale. An empty-string claim would make every request see a difference
    /// and reissue the ticket forever.
    /// </summary>
    [Fact]
    public void An_unset_palette_leaves_no_claim_behind()
    {
        var principal = UserPrincipal.Create(new User { Id = 1, Username = "someone" });

        Assert.Null(UserPrincipal.GetLightTheme(principal));
        Assert.Null(UserPrincipal.GetDarkTheme(principal));
        Assert.DoesNotContain(principal.Claims, c => c.Type == UserPrincipal.LightThemeClaim);
        Assert.DoesNotContain(principal.Claims, c => c.Type == UserPrincipal.DarkThemeClaim);
    }

    [Fact]
    public void An_anonymous_visitor_has_no_palettes()
    {
        var anonymous = new ClaimsPrincipal(new ClaimsIdentity());

        Assert.Null(UserPrincipal.GetLightTheme(anonymous));
        Assert.Null(UserPrincipal.GetDarkTheme(anonymous));
    }
}
